# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=512)),
                ('author_name', models.CharField(max_length=256)),
                ('author_id', models.IntegerField()),
                ('created_at', models.DateField()),
                ('tweet_id', models.IntegerField()),
            ],
        ),
    ]
